import Head from 'next/head'
import styles from '../styles/Home.module.css'

import {gql} from '@apollo/client'
import client from '../apolloClient'



export default function Home({streams}) {
  console.log(streams)



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       <h1>Hello World</h1>

      </main>

    </div>
  )
}

export async function getStaticProps(){
  const {data: streams} = await client.query({
    query: gql `
    
    query Streams {
      streams {
        title
    
      }
    }

    `
  })
  console.log(streams)
  return {
    props: {
      streams
    }
  }
}